[project]
name = "aiserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.4.0",
    "aiohttp>=3.11.13",
    "protobuf>=6.30.0",
    "sentencepiece>=0.2.0",
    "transformers>=4.49.0",
]
